### ISSUE TITLE
rosjava_extras is failing to build on kinetic

### ISSUE THREAD

**Issue by tfoote** [rosjava/rosjava_extras#21]
It looks to be the same issue with gradle version as https://github.com/rosjava/rosjava_core/issues/288

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__rosjava_extras__ubuntu_xenial_amd64__binary/

**Comment by jubeira** [comment]
Patch sent with fix: https://github.com/ros/rosdistro/pull/20029.

Thanks @tfoote!
