### ISSUE TITLE
Missing hydro-devel branch

### ISSUE THREAD

**Issue by adamantivm** [rosjava/rosjava_extras#5]
@stonier any chance you can quickly push a hydro-devel branch into this repo, as a copy of the current hydro branch?

Alternatively, we need to update https://github.com/rosjava/rosjava_tools/blob/hydro-devel/rosjava.rosinstall to point to the hydro branch of rosjava_extras.

Until either of those is fixed, the installation instructions in http://wiki.ros.org/sig/Rosjava/Android%20Development%20Environment are broken  :-/

**Comment by stonier** [comment]
Ach, my apologies mate. That was a big update last friday and I had intended to keep the old devel branches afloat while the new ones slipped under.

Pushed the old working hydro-devel branch back in.

**Comment by adamantivm** [comment]
No worries, that merge was tough work. We'll keep reporting what we find.
Key me know if we should do it differently or if we could contribute better
somehow.
